Fixup for "Fix message print string format"
    In file included from hal/drivers/mesa-hostmot2/hm2_soc_ol.c:108:0:
    hal/drivers/mesa-hostmot2/hm2_soc_ol.c: In function ‘instantiate’:
    hal/drivers/mesa-hostmot2/hm2_soc_ol.h:23:23: error:
        format ‘%u’ expects argument of type ‘unsigned int’, but
        argument 5 has type ‘size_t {aka long unsigned int}’ [-Werror=format=]
     #define HM2_LLIO_NAME "hm2_soc_ol"
                           ^
    hal/drivers/mesa-hostmot2/hostmot2-lowlevel.h:42:64: note:
        in expansion of macro ‘HM2_LLIO_NAME’
     #define LL_ERR(fmt, args...)   rtapi_print_msg(RTAPI_MSG_ERR,  HM2_LLIO_NAME ": " fmt, ## args);
                                                                    ^~~~~~~~~~~~~
    hal/drivers/mesa-hostmot2/hm2_soc_ol.c:610:13: note:
        in expansion of macro ‘LL_ERR’
                 LL_ERR("reading '%s': expected %u got %u - %s\n", brd->descriptor,
                 ^~~~~~
    cc1: all warnings being treated as errors