Revert `rtapi_shmem_getptr()` signature
Issue machinekit/machinekit#178 reported no way of retrieving a shm
segment's size.  PR machinekit/machinekit#179 (commit 4d85f079) fixed
this by adding an extra argument to `rtapi_shmem_getptr()`, breaking
the API.

This breaks building upstream LCNC against MK-HAL as follows:

    Compiling emc/motion/usrmotintf.cc
    g++ [...] emc/motion/usrmotintf.cc -o objects/emc/motion/usrmotintf.o
    emc/motion/usrmotintf.cc: In function ‘int usrmotInit(const char*)’:
    emc/motion/usrmotintf.cc:658:66: error:
           too few arguments to function
           ‘int rtapi_shmem_getptr(int, void**, long unsigned int*)’
         retval = rtapi_shmem_getptr(shmem_id, (void **) &emcmotStruct);
                                                                  ^
    In file included from emc/motion/usrmotintf.cc:35:0:
    [...]/include/rtapi.h:874:12: note: declared here
     extern int rtapi_shmem_getptr(int shmem_id, void **ptr, unsigned long int *size);
                ^~~~~~~~~~~~~~~~~~
    Makefile:223: recipe for target 'objects/emc/motion/usrmotintf.o' failed
    make: *** [objects/emc/motion/usrmotintf.o] Error 1

It turns out that the size is only needed in a single call in
`hal/lib/halmodule.cc`, and a dozen plus other calls ignore the size.

This patch reverts much of 4d85f079, and fixes
machinekit/machinekit#178 by adding a separate function
`rtapi_shmem_getsize()`, thus changing the API but not breaking it.